### ISSUE TITLE
Console spam from log with moment argument

### ISSUE THREAD

**Issue by marcus-nl** [RangerRick/moment-javaformat#1453]
In index.js there is the following line:
```JavaScript
    console.log("register:", moment, fatal);
```
When using Jest this causes a huge amount of text to be logged. It seems like the whole source code of the module is printed:
![Screenshot from 2024-02-14 13-48-20](https://github.com/RangerRick/moment-javaformat/assets/2447043/e29f1723-ee71-4f2d-8e7e-d33495b64d40)

It can be resolved by simply replacing the line with the following, or similar:
```JavaScript
    console.log("register: moment=%s, fatal=%s", typeof moment, fatal);
```

**Comment by RangerRick** [comment]
good catch! I'll go ahead and do a release today

**Comment by RangerRick** [comment]
(done)
